const bookCategories: string[] = [
  "Fiction",
  "Non-Fiction",
  "Mystery",
  "Fantasy",
  "Science Fiction",
  "Biography",
  "History",
  "Self-Help",
  "Romance",
  "Horror",
  "Thriller",
  "Poetry",
  "Philosophy",
  "Business",
  "Technology",
  "Science",
  "Health & Wellness",
  "Travel",
  "Cooking",
  "Art & Photography",
  "Children's Books",
  "Religion & Spirituality",
  "Comics & Graphic Novels",
  "Education",
  "Sports",
  "Politics",
  "True Crime",
  "Music",
  "Crafts & Hobbies",
  "Law"
];

export default bookCategories;
